spring.application.name=Agenda-contactos-springboot

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/agenda_contactos
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring,jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración personalizada de la documentación en Swagger
springdoc.openapi.info.title=API Sistema de Agenda de Contactos
springdoc.openapi.info.description=Documentación interactiva de los endpoints REST para la gestión de contactos vinculados a la base de datos MySQL.
springdoc.openapi.info.version=1.0.0

